name: release
on: push
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
  artifact_windows:
    needs: release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - run: chmod +x gradlew
      - run: ./gradlew build -x test
      - run: ./gradlew jpackage
      - id: upload_release_artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.steps.create_release.outputs.upload_url }}
          asset_path: ./build/jpackage/Spectral-1.0.3.exe
          asset_name: SpectralInstaller.exe
          asset_content_type: application/zip
