name: upload_artifacts
on:
  release:
    types: [published]
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - run: chmod +x gradlew
      - run: ./gradlew build -x test
      - run: ./gradlew jpackage
      - id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./build/jpackage/Spectral-1.0.3.exe
          asset_name: SpectralInstaller.exe
          asset_content_type: application/zip
